version: '3'  # 指定docker-compose的版本

services:
  modify_public_ip:  # 服务名称
    build:
      context: .  # 指定构建上下文为当前目录
      dockerfile: Dockerfile  # 指定Dockerfile文件
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
    volumes:
      - .:/app # 将宿主机的当前目录挂载到容器的/app目录
    restart: always  # 设置容器重启策略
    command: python main.py